elastic:
  urls: http://192.168.32.38:9200 # 多个逗号分开
  ssl:
    enable: false
    user: 'elastic'
    pwd: '123456'
    p12: E:\\data\\elastic\\elastic-certificates.p12
  # 多个以英文逗号分隔
  bulk_processor:
    btach_size: 1000 #文档数量达到指定阈值时提交
    bulk_size: 5 #总文档体积达到5M时提交，单位（MB）
    flush_interval: 5 #每隔多久提交一次(无论文档数量、体积是否达到阈值)单位（秒）
    concurrent_requests: 10 #发送bulk的并发线程数