# Spring配置
spring:
  application:
    name: ahead-doc
  profiles:
    #active: kafka,elastic,redis, dp
    active: logging, ds, dp,kafka,redis

logging:
  config: classpath:logback-spring.xml

soc:
  redis-sync: # 是否对redis数据进行同步
    enable: true
